window.victorylaboinfo = {
    company:{
        info:"会社名を㈱など省略せずに入力してください。",
        placeholder:"株式会社ビクトリー",
    },
    division:{
        info:"",
        placeholder:"",
    },
    address1:{
        info:"",
        placeholder:"",
    },
    department:{
        info:"",
        placeholder:"",
    },
    name:{
        info:"",
        placeholder:"",
    },
    contact:{
        info:"",
        placeholder:"",
    },
    mailaddress:{
        info:"",
        placeholder:"",
    },
    reportname:{
        info:"",
        placeholder:"",
    },
    reportcase:{
        info:"",
        placeholder:"",
    },
    onsite:{
        info:"",
        placeholder:"",
    },
    onsite_address:{
        info:"",
        placeholder:"",
    },
    manage_name:{
        info:"",
        placeholder:"",
    },
    plan:{
        info:"",
        placeholder:"",
    },
    resend:{
        info:"",
        placeholder:"",
    },
}